version: "3"
services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: qalasiaq-checkmk_server_1
      APP_PORT: 5000

  checkmk:
    image: checkmk/check-mk-raw:latest
    volumes:
      - ./data:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    restart: always